name: Deploy to GCS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: true 

    env:
        GCP_PROJECT_SECRET: ${{ secrets.PROJECT_SECRET }}
        GCS_SECRET: ${{ secrets.GCS_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK and auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Execute deployment script
        run: bash resources/Deployment/deployment.sh $GCP_PROJECT_SECRET $GCS_SECRET
