name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: true 

    env:
        GCP_AUTH: ${{ secrets.GCP_SA_KEY }}
        GCP_PROJECT_SECRET: ${{ secrets.GCS_SECRET }}
        GCS_SECRET: ${{ secrets.GCS_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: $GCP_AUTH
          project_id: 
          export_default_credentials: true

      - name: Execute deployment script
        run: bash deployment.sh $GCP_PROJECT_SECRET $GCS_SECRET
